# ????
spring:
  application:
    name: github-proxy
# ???
server:
  port: 10000


domains: raw.githubusercontent.com,github.com
file_suffixes: .ini,.yaml,.txt,.java,.py,.html,.css,.js,.ts,.md,.list

